defaults:
  - case: lm
  - _self_

device: cuda

amp:
  enable: true
  # fp16 or bf16
  dtype: bf16

torch_compile:
  enable: false
  # default, reduce-overhead, max-autotune, or max-autotune-no-cudagraphs
  mode: default

profiling:
  output_dir: profiles/default
  warmup_steps: 10
  exec_steps: 10
  forward_only: true
  nvtx:
    annotate_modules: true
    use_cudart_range: true
  memory_profiling:
    enable: true

hydra:
  run:
    dir: ${profiling.output_dir}
